// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlyhlnaioulbwjjigkrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndseWhsbmFpb3VsYndqamlna3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDk3NTIsImV4cCI6MjA2OTk4NTc1Mn0.vW1F_pooiZK6otz8FueSkcI0kSBTyEAwp7xbaKAu_9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});